version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
    container_name: backend-node
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always