name: Deploy MERN App

on:
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Frontend Image
      run: |
        cd frontend
        docker build -t frontend-app .

    - name: Build Backend Image
      run: |
        cd backend
        docker build -t backend-node .

